# Generated by Django 3.0.4 on 2020-03-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyarea',
            name='id',
        ),
        migrations.AddField(
            model_name='studyarea',
            name='slug',
            field=models.SlugField(default='', editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyarea',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
